### ISSUE TITLE
Add line number option

### ISSUE THREAD

**Issue by ducks** [redox-os/sodium#56]
Add options "line_numbers" and "ln" to toggle line numbers at the start of each line.

**Comment by rjgoldsborough** [comment]
@ticki, I've started an implementation of this here: https://github.com/rjgoldsborough/sodium/tree/add-line-number-option but wanted your thoughts on a few things.

1) Is what I'm doing so far sane I guess? I've added an option that toggles then just some code that prints a rectangle on each line.

2) I think we'd need to shift the window over when this option is on. I tried adding to pos_x if the option is set but that got funky in insert mode. Any ideas on that?

3) And then we obviously need to print out the line number. That's available with enumerate but that type is usize. I wanted to try to use the window.char but that accepts char and I'm not sure if it's possible to go usize to char and the best way. I looked at the code for how prompt prints stuff but wasn't sure if I needed to replicate that here since it's a bit more static and just print out a count of numbers. I also looked at the orbtk textbox widget but never got that working.

Any thoughts or ideas?

**Comment by ticki** [comment]
1) It looks fine. Haven't looked carefully, but the overall approach looks cool.

2) Not sure why that would be necessary.

3) I'd choose to count the bytes, and not the characters.

**Comment by rjgoldsborough** [comment]
2) because there will need to be room to display the line numbers without bumping into the editor window. vim shifts the window when toggling line number.

3) care to explain more? I'm currently counting lines in `current_buffer()` and getting the count with enumerate but am struggling with how to output the count in the editor window.

**Comment by dummie999** [comment]
Implemented, can be closed @jackpot51
